// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	entity "github.com/vnnyx/golang-api/entity"

	sqlx "github.com/jmoiron/sqlx"
)

// CustomerRepository is an autogenerated mock type for the CustomerRepository type
type CustomerRepository struct {
	mock.Mock
}

// CreateCustomer provides a mock function with given fields: ctx, tx, customer
func (_m *CustomerRepository) CreateCustomer(ctx context.Context, tx *sqlx.Tx, customer entity.Customer) (entity.Customer, error) {
	ret := _m.Called(ctx, tx, customer)

	var r0 entity.Customer
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, entity.Customer) entity.Customer); ok {
		r0 = rf(ctx, tx, customer)
	} else {
		r0 = ret.Get(0).(entity.Customer)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, entity.Customer) error); ok {
		r1 = rf(ctx, tx, customer)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteAllCustomer provides a mock function with given fields: ctx, tx
func (_m *CustomerRepository) DeleteAllCustomer(ctx context.Context, tx *sqlx.Tx) error {
	ret := _m.Called(ctx, tx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx) error); ok {
		r0 = rf(ctx, tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteCustomer provides a mock function with given fields: ctx, tx, customerId
func (_m *CustomerRepository) DeleteCustomer(ctx context.Context, tx *sqlx.Tx, customerId uint32) error {
	ret := _m.Called(ctx, tx, customerId)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uint32) error); ok {
		r0 = rf(ctx, tx, customerId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllCustomer provides a mock function with given fields: ctx, tx
func (_m *CustomerRepository) GetAllCustomer(ctx context.Context, tx *sqlx.Tx) ([]entity.Customer, error) {
	ret := _m.Called(ctx, tx)

	var r0 []entity.Customer
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx) []entity.Customer); ok {
		r0 = rf(ctx, tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Customer)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx) error); ok {
		r1 = rf(ctx, tx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCustomerById provides a mock function with given fields: ctx, tx, customerId
func (_m *CustomerRepository) GetCustomerById(ctx context.Context, tx *sqlx.Tx, customerId uint32) (entity.Customer, error) {
	ret := _m.Called(ctx, tx, customerId)

	var r0 entity.Customer
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uint32) entity.Customer); ok {
		r0 = rf(ctx, tx, customerId)
	} else {
		r0 = ret.Get(0).(entity.Customer)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, uint32) error); ok {
		r1 = rf(ctx, tx, customerId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByUsername provides a mock function with given fields: ctx, tx, username
func (_m *CustomerRepository) GetUserByUsername(ctx context.Context, tx *sqlx.Tx, username string) (entity.Customer, error) {
	ret := _m.Called(ctx, tx, username)

	var r0 entity.Customer
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, string) entity.Customer); ok {
		r0 = rf(ctx, tx, username)
	} else {
		r0 = ret.Get(0).(entity.Customer)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, string) error); ok {
		r1 = rf(ctx, tx, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateCustomer provides a mock function with given fields: ctx, tx, customer
func (_m *CustomerRepository) UpdateCustomer(ctx context.Context, tx *sqlx.Tx, customer entity.Customer) (entity.Customer, error) {
	ret := _m.Called(ctx, tx, customer)

	var r0 entity.Customer
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, entity.Customer) entity.Customer); ok {
		r0 = rf(ctx, tx, customer)
	} else {
		r0 = ret.Get(0).(entity.Customer)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, entity.Customer) error); ok {
		r1 = rf(ctx, tx, customer)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type NewCustomerRepositoryT interface {
	mock.TestingT
	Cleanup(func())
}

// NewCustomerRepository creates a new instance of CustomerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCustomerRepository(t NewCustomerRepositoryT) *CustomerRepository {
	mock := &CustomerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
